-- criar tabela CLIENTE, colunas CODCLI, NOME, E-MAIL, CODCLI chave primaria 
CREATE TABLE CLIENTE (
    CODCLI INTEGER NOT NULL PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL
);

-- criar tabela PRODUTO, colunas CP, NOMEPROD, DESCRI_PROD, CP como chave primaria
CREATE TABLE PRODUTO (
    CP INTEGER NOT NULL PRIMARY KEY,
    NOMEPROD VARCHAR(50) NOT NULL,
    DESCRI_PROD VARCHAR(50) NOT NULL
);

-- criar tabela VENDA, colunas CODCLI, CP, DATA, QUANT, VALOR e CODCLI referencia tabela CLIENTE(CODCLI) e CP referencia tabela PRODUTO(CP)
CREATE TABLE VENDA (
    CODCLI INTEGER NOT NULL,
    CP INTEGER NOT NULL,
    DATA DATE NOT NULL,
    QUANT INTEGER NOT NULL,
    VALOR FLOAT NOT NULL,
    FOREIGN KEY (CODCLI) REFERENCES CLIENTE(CODCLI) ON DELETE CASCADE,
    FOREIGN KEY (CP) REFERENCES PRODUTO(CP) ON DELETE CASCADE
);


